# Generated by Django 3.1.4 on 2020-12-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage_values',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('created', models.DateField()),
                ('down_payment_level', models.IntegerField()),
                ('first_mortgage', models.BooleanField()),
                ('long_amortization', models.BooleanField()),
                ('rate_type', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('posted', models.BooleanField()),
                ('refinance_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
