# Generated by Django 3.1.4 on 2020-12-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mortgage_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage_values',
            name='refinance_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
