# Generated by Django 3.1.4 on 2020-12-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mortgage_backend', '0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage_values',
            name='refinance_rate',
        ),
    ]
